### ISSUE TITLE
cannot install new plugins

### ISSUE THREAD

**Issue by chojuanillo** [jjethwa/rundeck#29] opened 2016-08-07 16:56 UTC
hello!. Thank you for this docker.

I am trying to install new plugins, but I have not succeeded . I put the .jar files in /opt/rundeck-plugins and restart the container , but do not appear plugins installed.

you can help me, please

**Comment by jjethwa** [comment] 2016-08-08 00:21
Hi @chojuanillo 

Are you using a volume for /opt/rundeck-plugins?  You will need to use a volume so your plugin persists through container restarts.

Do you see the plugin listed in the Settings menu after the restart?

**Comment by jjethwa** [comment] 2016-08-22 22:18
Hi @chojuanillo 

Just checking in with you on this issue.  I haven't had any other complaints about additions to /opt/rundeck-plugins not loading correctly.  Please let me know.  If I don't hear back in another few days, I'll close this issue.  Thanks :)

**Comment by jjethwa** [comment] 2016-11-01 20:44
Closing the issue as it is not reproducible and the user is not responding.  Please re-open if further support is needed.

**Comment by IvanAtanasov** [comment] 2017-01-27 12:12
I'm having this same problem. Think the cause is that the /opt/run script just does a cp from /opt/rundeck-plugins which results in the files being owned by root. This could be fixed by using something like: 

```shell
install -o rundeck -g rundeck -m 0644 /opt/rundeck-plugins/*.zip /var/lib/rundeck/libext 2>/dev/null
```

**Comment by jjethwa** [comment] 2017-01-27 19:47
Hi @IvanAtanasov 

Is this occurring with the latest container that was built ~2 days ago?  This commit should have fixed it: https://github.com/jjethwa/rundeck/commit/b373b467644d57222034ecc7f710c08294a0f2d0

**Comment by IvanAtanasov** [comment] 2017-01-31 15:06
Hi @jjethwa 

I'm using the version tagged 2.7.1.

I think even the latest version will have the same problem. As it is still simply doing a cp command, the permissions of the original file will be maintained. This means that it relies on the source plugin file being readable by other users (assuming it is not owned by rundeck).

**Comment by jjethwa** [comment] 2017-01-31 19:40
Hi @IvanAtanasov 

https://github.com/jjethwa/rundeck/commit/a587f97e32fb5131dcc78000cd15e4ebc66b2d72 should fix it 😄

**Comment by IvanAtanasov** [comment] 2017-02-01 10:07
:+1:  That'll do it @jjethwa

**Closed** 2017-02-01 10:21 UTC
